[package]
name = "excalidraw-document-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
excalidraw-document = { path = "../crates/excalidraw-document", features = ["embedded"] }

libfuzzer-sys = "0.4"

[[bin]]
name = "document"
path = "fuzz_targets/document.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
